export const GOOGLE_CALENDAR_CODES = {
    /* ========= SUCCESS (22xxx) ========= */
    GOOGLE_AUTH_URL_GENERATED: 22001,
    GOOGLE_CONNECTED: 22002,
    GOOGLE_DISCONNECTED: 22003,
    GOOGLE_IMPORT_SUCCESS: 22004,
    GOOGLE_EXPORT_SUCCESS: 22005,
    GOOGLE_SYNC_COMPLETED: 22006,

    /* ========= CLIENT / INTEGRATION ERRORS (42xxx) ========= */
    GOOGLE_NOT_CONNECTED: 42001,
    GOOGLE_INVALID_CALLBACK: 42002,
    GOOGLE_TOKEN_EXPIRED: 42003,
    GOOGLE_CONFLICT_DETECTED: 42004,
    GOOGLE_INSUFFICIENT_SCOPES: 42005,

    /* ========= SERVER ERRORS (52xxx) ========= */
    GOOGLE_SYNC_FAILED: 52001,
    GOOGLE_TOKEN_SAVE_FAILED: 52002,
    GOOGLE_INTERNAL_ERROR: 52003,
} as const;

export type GoogleCalendarCode =
    typeof GOOGLE_CALENDAR_CODES[keyof typeof GOOGLE_CALENDAR_CODES];
